# Simple workflow for deploying static content to GitHub Pages
name: Create release

on:
  push:
    tags:
      - 'v[0-9]+'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  issues: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  testing:
    uses: './.github/workflows/pull-request-check.yml'

  create-changelog-and-issue:
    needs: [testing]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Get info
        id: info
        shell: bash
        run: |
          currentVersion=${{ github.ref_name }}
          echo "currentVersion=${currentVersion}" >> $GITHUB_OUTPUT
          echo "previousVersion=${previousVersion}" >> $GITHUB_OUTPUT
          echo "author=${{ github.actor }}" >> $GITHUB_OUTPUT
          echo "createDate=$(date +'%D %H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Create CHANGELOG
        id: changelog
        uses: ardalanamini/auto-changelog@v4
        with:
          semver: false

      - name: Create Release Issue
        id: issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.info.outputs.currentVersion }}
          DATE: ${{ steps.info.outputs.createDate }}
          AUTHOR: ${{ steps.info.outputs.author }}
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
        with:
          filename: .github/ISSUE_TEMPLATE.md
          update_existing: true
          search_existing: all
          assignees: ${{ github.actor }}

      - name: Add link to tests
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ steps.issue.outputs.number }}
          body: |
            Результаты тестов: ${{ needs.testing.outputs.testsUrl }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      issueNumber: ${{ steps.issue.outputs.number }}

  build-and-deploy:
    needs: [testing]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Create release branch
        shell: bash
        run: |
          git checkout -b release-${{ github.ref_name }}
          git push -u origin release-${{ github.ref_name }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          token: ${{ secrets.GH_PAT }}

  close-issue:
    needs: [testing, create-changelog-and-issue, build-and-deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Add link to pages
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ needs.create-changelog-and-issue.outputs.issueNumber }}
          body: |
            Ссылка на сайт: https://Terro216.github.io/infrastructure-hw/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ needs.create-changelog-and-issue.outputs.issueNumber }}
          comment: Issue successfully closed
